-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `congreso_db` DEFAULT CHARACTER SET utf8 ;
USE `congreso_db` ;


CREATE TABLE IF NOT EXISTS `congreso_db`.`alumnos` (
  `no_control` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `estado` ENUM('PENDIENTE', 'RECHAZADO', 'ACEPTADO') NOT NULL DEFAULT 'PENDIENTE',
  `telefono` VARCHAR(10) NOT NULL,
  `grado` INT NOT NULL,
  `grupo` VARCHAR(1) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contra` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`no_control`),
  UNIQUE INDEX `no_control_UNIQUE` (`no_control` ASC) VISIBLE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `congreso_db`.`talleres` (
  `taller_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `tallerista` VARCHAR(45) NOT NULL,
  `cupo` INT NOT NULL,
  `lugar` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`taller_id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `congreso_db`.`alumno_taller` (
  `alumno_taller_id` INT NOT NULL AUTO_INCREMENT,
  `alumnos_no_control` INT NOT NULL,
  `talleres_taller_id` INT NOT NULL,
  PRIMARY KEY (`alumno_taller_id`),
  INDEX `fk_alumno_taller_alumnos_idx` (`alumnos_no_control` ASC) VISIBLE,
  INDEX `fk_alumno_taller_talleres1_idx` (`talleres_taller_id` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_taller_alumnos`
    FOREIGN KEY (`alumnos_no_control`)
    REFERENCES `congreso_db`.`alumnos` (`no_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_taller_talleres1`
    FOREIGN KEY (`talleres_taller_id`)
    REFERENCES `congreso_db`.`talleres` (`taller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `congreso_db`.`alumno_pago` (
  `idalumno_pago` INT NOT NULL AUTO_INCREMENT,
  `alumnos_no_control` INT NOT NULL,
  `fecha_subida` TIMESTAMP NOT NULL,
  `ruta` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idalumno_pago`),
  INDEX `fk_alumno_pago_alumnos1_idx` (`alumnos_no_control` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_pago_alumnos1`
    FOREIGN KEY (`alumnos_no_control`)
    REFERENCES `congreso_db`.`alumnos` (`no_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `congreso_db`.`usuarios_staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL UNIQUE,
  `contra` VARCHAR(255) NOT NULL,
  `rol` ENUM('ADMIN', 'SUBADMIN') NOT NULL DEFAULT 'SUBADMIN',
  `activo` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `congreso_db`.`congreso_info` (
  `congreso_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `banner_ruta` VARCHAR(255) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`congreso_id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `congreso_db`.`tarjeta_info` (
  `tarjeta_info_id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `subtitulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `imagen_ruta` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`tarjeta_info_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
